export const taskDescriptionFieldMarkdownLabels = {
  bold: "**Bold**",
  italic: "*Italic*",
  strikethrough: "~~Strikethrough~~",
  inlineCode: "`Inline code`",
  link: "[Link](https://www.google.com)",
  headingOne: "# Heading 1",
  headingTwo: "## Heading 2",
  headingThree: "### Heading 3",
  headingFour: "#### Heading 4",
  headingFive: "##### Heading 5",
  headingSix: "###### Heading 6",
  numericList: "1. Numbered list",
  bulletedList: "* Bulleted list",
  quote: "> Quote",
  codeBlock: "```\nCode block\n```",
  divider: "---",
  image: "![Image alt](https://www.google.com)",
};
